# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: /
  Archives: archives

social:
  email: florist.sk@gmail.com
  twitter: leafbird_tw
  weibo:
  github: leafbird
  googleplus:
  rss: http://feeds.feedburner.com/florist_devnote

# Content
fancybox: true # set to true if you want to use it

duoshuo: #duoshuo_shortname
disqus: leafbirddev #disqus _shortname
google_analytics: UA-52787243-1 #Google Analytics Tracking Code
google_adsense_page_level_ads: #Google Adsense Page Level Ads Code
